package com.athena.security;

public enum ApplicationUserPermission {

    USER_PII_READ,
    USER_PII_WRITE,
    USER_GOAL_READ,
    USER_GOAL_WRITE,
    USER_MILESTONE_READ,
    USER_MILESTONE_WRITE,
    USER_OBJECTIVE_READ,
    USER_OBJECTIVE_WRITE,
    USER_TASK_READ,
    USER_TASK_WRITE,
    USER_CALENDAR_READ,
    USER_CALENDAR_WRITE,
    ADMINISTRATOR

}
